### ISSUE TITLE
Jackson 설정

### ISSUE THREAD

**Issue by MaximSungmo** [Web-AtoZ/Spring#24]
jackson property strategy 설정 및 원리 간략 준비.

**Comment by Yujaehyeong** [comment]
properties 파일에 네이밍컨벤션설정하여  응답시, 설정 값대로 응답하는 것을 확인하였습니다. -> 모든 응답 값에 대한 네이밍컨벤션 설정이 통일됨
* 응답 값의 네이밍 컨벤션을 설정하는건 API 제공하는 사람 마음대로지만, 문득생각이 든것이 Controller에서 응답하는 시점에 네이밍컨벤션을 설정하는 방법도 필요할것 같습니다.
