### ISSUE TITLE
프로젝트 세팅

### ISSUE THREAD

**Issue by Soobinnn** [Web-AtoZ/Spring#3]
1. LogBack설정하기
2. DB 연동 
   2-1. Mybatis
   2-2. JPA
3. 코드 컨벤션 세팅 (CodeStyle)
4. 프로젝트 디렉토리 구조 세팅 (Layerd Architecture)
5. 정적분석(SonarQube) 세팅
6. Jenkins 연동해서 자동 배포

**Comment by Soobinnn** [comment]
@MaximSungmo 추가의견있습니까?

**Comment by MaximSungmo** [comment]
@Soobinnn  현재까지는 없습니다. 깔끔하게 잘 정리해주셨네요!
