### ISSUE TITLE
Test case 작성하기

### ISSUE THREAD

**Issue by MaximSungmo** [Web-AtoZ/Spring#38]
[ ] 테스트 케이스 
*  [x] Controller에서 데이터 router 통해서 받기
*  [x] Service 로직 확인하기 

JUNIT 5로 Dependency 걸거나 혹은 본인이 확인 중 괜찮다 싶은 것으로 작업 후 설명

**Comment by Yujaehyeong** [comment]
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':detachedConfiguration123'.
   > Could not resolve org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.3.3.
     Required by:
         project :
      > Cannot choose between the following variants of org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.3.3:
          - enforcedRuntimeElements
          - runtimeElements
        All of them match the consumer attributes:
          - Variant 'enforcedRuntimeElements' capability org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.3.3:
              - Unmatched attributes:
                  - Found org.gradle.category 'enforced-platform' but wasn't required.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.gradle.usage 'java-runtime' but wasn't required.
          - Variant 'runtimeElements' capability org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.3.3:
              - Unmatched attributes:
                  - Found org.gradle.category 'platform' but wasn't required.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.gradle.usage 'java-runtime' but wasn't required.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 930ms

---------------------------------------------
* https://javadeveloperzone.com/spring-boot/spring-boot-request-routing-example/
이 링크 그대로 따라하면 될거같은데 왜 위와 같은 오류가 나는지 모르겠습니다.
