### ISSUE TITLE
DB 연동 - MyBatis

### ISSUE THREAD

**Issue by Soobinnn** [Web-AtoZ/Spring#6]
DB 연동 - MyBatis

**Comment by MaximSungmo** [comment]
@hanseonghye  

Mybatis 쿼리문에서 if 문 걸기 (동적 쿼리)
select * from domain where a = {a} if( ! b.isEmpty) { and b=b}

Mybatis 를 DataSource에서 Configuration 작업하기 
목적 : camelCase인 domain의 멤버변수를 table의 snake_case랑 어떻게 매칭시킬지? 
키워드 : mybatis camel to snake_case
