### ISSUE TITLE
DB 연동 - JPA

### ISSUE THREAD

**Issue by Soobinnn** [Web-AtoZ/Spring#7]
DB 연동 - JPA설정

**Comment by MaximSungmo** [comment]
@mshero7  
상수님, JPA 제가 git으로 현 이슈번호의 브랜치로 따서 진행할 예정입니다.
해당 브랜치를 pull 받으시고 작업 진행해주시면 되고  작업 내용은 다음과 같습니다.

JPA 설정 코드 읽기 
JPA Query 진행해보기 

* [ ] @Query(" ~~  ") - RUD
* [ ] @Query(" ", nativeQuery = true) - CRUD
* [ ] 메소드명으로 쿼리작업  Select, Update, Delete
* [ ] 데이터 insert 

중간 중간 질문있으면 주세요.
